/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.pos.view;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.pos.controller.ManageCustomersController;
import lk.ijse.pos.controller.ManageItemsController;
import lk.ijse.pos.controller.ManageOrdersController;
import lk.ijse.pos.dto.CustomerDTO;
import lk.ijse.pos.dto.ItemDTO;
import lk.ijse.pos.dto.OrderDTO;
import lk.ijse.pos.dto.OrderDetailDTO;

/**
 *
 * @author janith
 */
public class ManageOrders extends javax.swing.JDialog {

    DefaultTableModel cartModel;
    DefaultTableModel allOrdersModel;

    /**
     * Creates new form ManageOrders
     */
    public ManageOrders(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cartModel = (DefaultTableModel) tblCart.getModel();
        allOrdersModel = (DefaultTableModel) tblAllOrders.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPaneAllOrders = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        btnPlaceOrder = new javax.swing.JButton();
        btnDeleteOrder = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtItemDesc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQtyOnHand = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUnitPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        btnAddToCart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAllOrders = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(752, 494));
        setResizable(false);

        TabbedPaneAllOrders.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        TabbedPaneAllOrders.setFocusable(false);
        TabbedPaneAllOrders.setMaximumSize(new java.awt.Dimension(752, 494));
        TabbedPaneAllOrders.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TabbedPaneAllOrdersFocusGained(evt);
            }
        });
        TabbedPaneAllOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabbedPaneAllOrdersMouseClicked(evt);
            }
        });

        jLabel2.setDisplayedMnemonic('S');
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Customer ID :");

        txtCustomerId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerIdActionPerformed(evt);
            }
        });

        jLabel3.setDisplayedMnemonic('S');
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Customer Name :");

        txtCustomerName.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel4.setDisplayedMnemonic('S');
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Order ID :");

        txtOrderId.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item code", "Quantity", "Unit Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCart);

        btnPlaceOrder.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/asset/add.png"))); // NOI18N
        btnPlaceOrder.setMnemonic('N');
        btnPlaceOrder.setText("Place Oder");
        btnPlaceOrder.setToolTipText("Click to add new subject");
        btnPlaceOrder.setFocusPainted(false);
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        btnDeleteOrder.setText("Delete");
        btnDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrderActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(197, 197, 197));

        jLabel5.setDisplayedMnemonic('S');
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Item Code :");

        txtItemCode.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemCodeActionPerformed(evt);
            }
        });

        jLabel6.setDisplayedMnemonic('S');
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Item Description :");

        txtItemDesc.setEditable(false);
        txtItemDesc.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel7.setDisplayedMnemonic('S');
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Qty on Hand :");

        txtQtyOnHand.setEditable(false);
        txtQtyOnHand.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel8.setDisplayedMnemonic('S');
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Unit Price :");

        txtUnitPrice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel9.setDisplayedMnemonic('S');
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Qty :");

        txtQty.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        btnAddToCart.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAddToCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/pos/asset/add.png"))); // NOI18N
        btnAddToCart.setMnemonic('N');
        btnAddToCart.setText("Add to Cart");
        btnAddToCart.setToolTipText("Click to add new subject");
        btnAddToCart.setFocusPainted(false);
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 147, Short.MAX_VALUE))
                    .addComponent(txtItemDesc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtQtyOnHand, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btnAddToCart)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItemDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtyOnHand, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddToCart))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnDeleteOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPlaceOrder))
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerName))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCustomerId, txtOrderId});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlaceOrder)
                    .addComponent(btnDeleteOrder)))
        );

        TabbedPaneAllOrders.addTab("New Order", jPanel1);

        tblAllOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "Customer Id", "Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAllOrders);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );

        TabbedPaneAllOrders.addTab("All Orders", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneAllOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneAllOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearAllFields() {
        cartModel.setRowCount(0);
        txtOrderId.setText("");
        txtCustomerId.setText("");
        txtCustomerName.setText("");
        txtItemCode.setText("");
        txtItemDesc.setText("");
        txtQtyOnHand.setText("");
        txtQty.setText("");
        txtUnitPrice.setText("");

    }

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
        String itemCode = txtItemCode.getText();
        double unitPrice = Double.parseDouble(txtUnitPrice.getText());
        double qty = Double.parseDouble(txtQty.getText());
        double total = unitPrice * qty;
        int row = -1;
        int rowCount = cartModel.getRowCount();

        if (rowCount > 0) {
            for (int i = 0; i < rowCount; i++) {
                if (cartModel.getValueAt(i, 0).equals(itemCode)) {
                    row = i;
                    break;
                }
            }
        }

        if (row == -1) {
            cartModel.addRow(new Object[]{itemCode, qty, unitPrice, total});
        } else {
            qty += Double.parseDouble("" + cartModel.getValueAt(row, 1));
            total += Double.parseDouble("" + cartModel.getValueAt(row, 3));
            cartModel.setValueAt(qty, row, 1);
            cartModel.setValueAt(total, row, 3);
            row = -1;
        }

    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void txtCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIdActionPerformed
        try {
            String customerId = txtCustomerId.getText();

            CustomerDTO dto = ManageCustomersController.findCustomer(customerId);
            txtCustomerName.setText(dto.getName());
        } catch (Exception ex) {
            Logger.getLogger(ManageOrders.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showConfirmDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_txtCustomerIdActionPerformed

    private void txtItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCodeActionPerformed
        try {
            String itemCode = txtItemCode.getText();

            ItemDTO dto = ManageItemsController.findItem(itemCode);

            if (null != dto) {
                txtItemDesc.setText(dto.getDescription());
                txtQtyOnHand.setText("" + dto.getQtyOnHand());
                txtUnitPrice.setText("" + dto.getUnitPrice());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Item cannot be found");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageOrders.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_txtItemCodeActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        try {
            OrderDTO orderDTO = new OrderDTO();
            List<OrderDetailDTO> orderDetailDTOs = new ArrayList<>();
            int rowCount = cartModel.getRowCount();

            orderDTO.setCustomerId(txtCustomerId.getText());
            orderDTO.setOrderId(txtOrderId.getText());
            orderDTO.setDate(new Date(System.currentTimeMillis()));

            for (int i = 0; i < rowCount; i++) {
                orderDetailDTOs.add(new OrderDetailDTO(
                        orderDTO.getOrderId(),
                        cartModel.getValueAt(i, 0).toString(),
                        Double.parseDouble(cartModel.getValueAt(i, 2).toString()),
                        Double.parseDouble(cartModel.getValueAt(i, 1).toString())
                ));
            }

            orderDTO.setOrderDetails(orderDetailDTOs);
            clearAllFields();
            if (ManageOrdersController.saveItem(orderDTO)) {
                JOptionPane.showMessageDialog(rootPane, "Successfully saved");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Order could not be placed");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageOrders.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }

    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrderActionPerformed
        try {
            String orderId = txtOrderId.getText();
            boolean result = ManageOrdersController.deleteOrder(orderId);

            if (result) {
                JOptionPane.showMessageDialog(rootPane, "Successfully deleted");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Order could not be deleted");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteOrderActionPerformed

    private void TabbedPaneAllOrdersFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TabbedPaneAllOrdersFocusGained
        try {
            System.out.println("Focus gained");
            List<OrderDTO> allOrders = ManageOrdersController.getAllOrders();

            if (!allOrders.isEmpty()) {
                allOrdersModel.setRowCount(0); //setting row count to 0 upon gaining focus 
                for (OrderDTO order : allOrders) {
                    allOrdersModel.addRow(new Object[]{
                        order.getOrderId(),
                        order.getCustomerId(),
                        order.getDate(),
                        order.getInvoiceAmount()
                    });
                }
            } else {

            }
        } catch (Exception ex) {
            Logger.getLogger(ManageOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TabbedPaneAllOrdersFocusGained

    private void TabbedPaneAllOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabbedPaneAllOrdersMouseClicked
        // TODO add your handling code here:
        try {
            System.out.println("Focus gained");
            List<OrderDTO> allOrders = ManageOrdersController.getAllOrders();

            if (!allOrders.isEmpty()) {
                allOrdersModel.setRowCount(0); //setting row count to 0 upon gaining focus 
                for (OrderDTO order : allOrders) {
                    allOrdersModel.addRow(new Object[]{
                        order.getOrderId(),
                        order.getCustomerId(),
                        order.getDate(),
                        order.getInvoiceAmount()
                    });
                }
            } else {

            }
        } catch (Exception ex) {
            Logger.getLogger(ManageOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TabbedPaneAllOrdersMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPaneAllOrders;
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAllOrders;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemDesc;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtQtyOnHand;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
}
